spring:
  cloud:
    function:
      definition: batchPublish
    stream:
      bindings:
        batchPublish-in-0:
          destination: 'batch/publish/trigger'
          group: batch
        batchPublish-out-0:
          destination: 'batch/consume/topic'
      binders:
        solace-broker:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
server:
  port: 8095                                